#! /bin/sh

#  ▄▄▄▄     ██████  ██▓███   █     █░ ███▄ ▄███▓ ██▀███   ▄████▄   
# ▓█████▄ ▒██    ▒ ▓██░  ██▒▓█░ █ ░█░▓██▒▀█▀ ██▒▓██ ▒ ██▒▒██▀ ▀█   
# ▒██▒ ▄██░ ▓██▄   ▓██░ ██▓▒▒█░ █ ░█ ▓██    ▓██░▓██ ░▄█ ▒▒▓█    ▄  
# ▒██░█▀    ▒   ██▒▒██▄█▓▒ ▒░█░ █ ░█ ▒██    ▒██ ▒██▀▀█▄  ▒▓▓▄ ▄██▒ 
# ░▓█  ▀█▓▒██████▒▒▒██▒ ░  ░░░██▒██▓ ▒██▒   ░██▒░██▓ ▒██▒▒ ▓███▀ ░ 
# ░▒▓███▀▒▒ ▒▓▒ ▒ ░▒▓▒░ ░  ░░ ▓░▒ ▒  ░ ▒░   ░  ░░ ▒▓ ░▒▓░░ ░▒ ▒  ░ 
# ▒░▒   ░ ░ ░▒  ░ ░░▒ ░       ▒ ░ ░  ░  ░      ░  ░▒ ░ ▒░  ░  ▒    
#  ░    ░ ░  ░  ░  ░░         ░   ░  ░      ░     ░░   ░ ░         
#  ░            ░               ░           ░      ░     ░ ░       
#       ░                                                ░         

## GENERAL
bspc config border_width           0
bspc config window_gap         	   5
bspc config left_padding       	   0
bspc config bottom_padding    	   0
bspc config split_ratio        	   0.50
bspc config focus_follows_pointer  true

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc rule -a Zathura state=tiled
bspc rule -a Scilab state=floating
