#! /bin/sh

#  ▄▄▄▄     ██████  ██▓███   █     █░ ███▄ ▄███▓ ██▀███   ▄████▄   
# ▓█████▄ ▒██    ▒ ▓██░  ██▒▓█░ █ ░█░▓██▒▀█▀ ██▒▓██ ▒ ██▒▒██▀ ▀█   
# ▒██▒ ▄██░ ▓██▄   ▓██░ ██▓▒▒█░ █ ░█ ▓██    ▓██░▓██ ░▄█ ▒▒▓█    ▄  
# ▒██░█▀    ▒   ██▒▒██▄█▓▒ ▒░█░ █ ░█ ▒██    ▒██ ▒██▀▀█▄  ▒▓▓▄ ▄██▒ 
# ░▓█  ▀█▓▒██████▒▒▒██▒ ░  ░░░██▒██▓ ▒██▒   ░██▒░██▓ ▒██▒▒ ▓███▀ ░ 
# ░▒▓███▀▒▒ ▒▓▒ ▒ ░▒▓▒░ ░  ░░ ▓░▒ ▒  ░ ▒░   ░  ░░ ▒▓ ░▒▓░░ ░▒ ▒  ░ 
# ▒░▒   ░ ░ ░▒  ░ ░░▒ ░       ▒ ░ ░  ░  ░      ░  ░▒ ░ ▒░  ░  ▒    
#  ░    ░ ░  ░  ░  ░░         ░   ░  ░      ░     ░░   ░ ░         
#  ░            ░               ░           ░      ░     ░ ░       
#       ░                                                ░         

bspc config border_width           3
bspc config window_gap             5
bspc config split_ratio            0.50
bspc config focus_follows_pointer  true

bspc config normal_border_color    "#212121"
bspc config active_border_color    "#EEFFFF"
bspc config focused_border_color   "#EEFFFF"

bspc rule -a Zathura state=tiled
bspc rule -a Scilab state=floating
bspc rule -a Spotify desktop=^6

.local/bin/configure_env.sh
