#! /bin/sh

#  ▄▄▄▄     ██████  ██▓███   █     █░ ███▄ ▄███▓ ██▀███   ▄████▄   
# ▓█████▄ ▒██    ▒ ▓██░  ██▒▓█░ █ ░█░▓██▒▀█▀ ██▒▓██ ▒ ██▒▒██▀ ▀█   
# ▒██▒ ▄██░ ▓██▄   ▓██░ ██▓▒▒█░ █ ░█ ▓██    ▓██░▓██ ░▄█ ▒▒▓█    ▄  
# ▒██░█▀    ▒   ██▒▒██▄█▓▒ ▒░█░ █ ░█ ▒██    ▒██ ▒██▀▀█▄  ▒▓▓▄ ▄██▒ 
# ░▓█  ▀█▓▒██████▒▒▒██▒ ░  ░░░██▒██▓ ▒██▒   ░██▒░██▓ ▒██▒▒ ▓███▀ ░ 
# ░▒▓███▀▒▒ ▒▓▒ ▒ ░▒▓▒░ ░  ░░ ▓░▒ ▒  ░ ▒░   ░  ░░ ▒▓ ░▒▓░░ ░▒ ▒  ░ 
# ▒░▒   ░ ░ ░▒  ░ ░░▒ ░       ▒ ░ ░  ░  ░      ░  ░▒ ░ ▒░  ░  ▒    
#  ░    ░ ░  ░  ░  ░░         ░   ░  ░      ░     ░░   ░ ░         
#  ░            ░               ░           ░      ░     ░ ░       
#       ░                                                ░         

bspc config border_width           5
bspc config window_gap             5
bspc config left_padding           0
bspc config bottom_padding         0
bspc config split_ratio            0.50
bspc config focus_follows_pointer  true

bspc config normal_border_color    "#212121"
bspc config active_border_color    "#EEFFFF"
bspc config focused_border_color   "#EEFFFF"

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc rule -a Zathura state=tiled
bspc rule -a Scilab state=floating
