#!/bin/sh

## Colors
bold=$(tput bold)
normal=$(tput sgr0)
red="\e[1;31m"
green="\e[1;32m"
nrm="\e[0m"

## Aliases
alias sd='sudo'
alias ls='ls --color=auto'
alias la='ls -la --color=auto'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias chx='chmod +x'
alias rb='sudo shutdown -r now'
alias p='sudo shutdown -h now'

alias q='pacman -Ss'
alias i='sudo pacman -S'
alias u='sudo pacman -Syyu'
alias r='sudo pacman -Rscn'
alias c='asd'

alias gs='git status'
alias ga='git add --all'
alias gl='git pull'
alias gc='git commit -m'
alias gp='git push --set-upstream origin master'

alias dt='cd $HOME/Desktop'
alias dl='cd $HOME/Downloads'
alias dev='cd $HOME/Dev'

alias dcu='docker-compose up -d'
alias dsc='docker stop $(docker ps -a -q)'
alias drd='docker stop $(docker ps -a -q)'
alias dri='docker rmi $(docker images -q)'