#!/bin/sh

 ####################################
 #           COLOR PALLETE          #
 ####################################

bold=$(tput bold)
normal=$(tput sgr0)
red="\e[1;31m"
green="\e[1;32m"
nrm="\e[0m"

 ####################################
 #          LIST OF ALIASES         #
 ####################################

alias sd='sudo'
alias ls='ls --color=auto'
alias la='ls -la --color=auto'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias chx='chmod +x'
alias rb='sudo shutdown -r now'
alias p='sudo shutdown -h now'

alias q='pa'
alias i='sudo apt install'
alias u='sudo apt update'
alias r='sudo apt purge'
alias c='sudo apt autoremove'

alias gs='git status'
alias ga='git add --all'
alias gl='git pull'
alias gc='git commit -m'
alias gp='git push --set-upstream origin master'

alias dt='cd $HOME/Desktop'
alias dl='cd $HOME/Downloads'
alias dev='cd $HOME/Dev'

alias checkupdates='\
echo "${bold}Checking Pacman...${normal}" \
&& checkupdates || echo -e "${green}󰕥  Up To Date${nrm}";\
echo "\n${bold}Checking the AUR...${normal}" \
&& [ -z "$(yay -Qum)" ] \
&& echo -e "${green}󰕥  Up To Date${nrm}" || yay -Qum ;\
dunstify -u low "Pacman" "Finished checking for updates."'