#!/bin/bash
# requires jq
# Author: https://github.com/BelkaDev

urlencode() {
echo ${1// /"%20"}
}

#settings
lang="pt"
country="br"
#######

url="http://suggestqueries.google.com/complete/search?client=chrome&hl=$lang&gl=$br&ds=yt&q=$(urlencode "$*")"
res=$(jq -r '.[1] | .[]' <<< "$(curl -s "$url" &)" | tr -d '"')
echo "$res"
